name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          CNAME: dicedornot.vengefulpickle.com
      - name: Notify
        uses: cpennington/action-discord@template-embeds
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_AVATAR: https://dicedornot.vengefulpickle.com/dicedornot-logo.png
          DISCORD_EMBEDS: >
            [
              <% _.forEach(EVENT_PAYLOAD.commits, function(commit) {%>
              {
                "author": {
                  "name": "{{commit.author.name}}",
                  "url": "https://github.com/{{commit.author.username}}",
                  "icon_url": "https://github.com/{{commit.author.username}}.png"
                },
                "title": "{{commit.message.split('\n')[0]}}",
                "description": "{{commit.message.split('\n').slice(1).join('\n')}}"
                "fields": [{
                  "name": "links",
                  "value": "[commit]({{commit.url}})"
                }],
                "footer": {
                  "text": "{{commit.timestamp}} | ${commit.id.substr(0,7)}"
                }
              }
              <%}); %>
            ]
